//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneBookApp.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacts
    {
        public long Id { get; set; }
        public string ContactName { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<long> UserReferenceId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
